# Generated by Django 3.1.13 on 2023-06-01 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生信息表',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='职工号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=20, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师信息表',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='名称')),
                ('time', models.IntegerField(help_text='单位是分钟', verbose_name='考试时长')),
                ('examtime', models.DateTimeField(verbose_name='考试时间')),
                ('fee', models.IntegerField(null=True, verbose_name='费用')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_xuehao', to='exam.student', verbose_name='学号')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_test', to='exam.testpaper', verbose_name='考试')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.TextField(verbose_name='题目')),
                ('qtype', models.CharField(choices=[('单选', '单选'), ('主观', '主观')], max_length=40, verbose_name='题目类型')),
                ('a', models.CharField(max_length=40, verbose_name='A选项')),
                ('b', models.CharField(max_length=40, verbose_name='B选项')),
                ('c', models.CharField(max_length=40, verbose_name='C选项')),
                ('d', models.CharField(max_length=40, verbose_name='D选项')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('middle', '中等'), ('difficult', '难')], max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.testpaper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paid', models.BooleanField(choices=[(0, '否'), (1, '是')], verbose_name='是否付款')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student', verbose_name='学号')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.testpaper', verbose_name='序号')),
            ],
            options={
                'verbose_name': '预订信息',
                'verbose_name_plural': '预订考试及付款信息表',
            },
        ),
        migrations.CreateModel(
            name='Answer_Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.TextField(verbose_name='题目')),
                ('answer', models.TextField(verbose_name='答案')),
                ('score', models.IntegerField(default=1000, verbose_name='得分')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questionbank', verbose_name='题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student', verbose_name='学生')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.testpaper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '答题记录和评分',
                'verbose_name_plural': '答题记录和评分',
            },
        ),
    ]
